apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: hassio
  name: hassio
addressType: IPv4
endpoints:
  - addresses:
      - {{ .Values.endpoint.ip }}
    conditions:
      ready: true
ports:
  - name: hassio
    port: 8123
    protocol: TCP
