apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt-{{ .Values.ingress.environment }}
  name: hassio
spec:
  hostnames:
  - {{ .Values.ingress.host0 }}
  parentRefs:
  - name: shared-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: hassio
      port: 443
    matches:
    - path:
        type: PathPrefix
        value: /
