apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-bearer-token
spec:
  encryptedData:
    token: AgA69YnCQq3sPEkVo4+XFXP0VNaYvyQfhr4t0S6fWKhkMs+fLre3mmpHhMkxubiQQU6glSWxwirWH+fOqXAzVGUx4hYAjkPtXf389gsW/cDmkN/n75iTaJA8xHYY5qMXFSojZ2P94k6xEMAcVSniShR26om7q2vLZApsSf/5S1eUNK/CDtI24Y7tIXYfaybCn5FXH7Lo4gs9DHaWvSRYWW9I/TXxklrJXwtiHngolISTZZ2DCnyBMyU1QcVTAf+Saf6jemjVP37J6MHgcdMtFdVgbwVwdMTz5SyXgfYImIqlrdyPwSvNYXhr++LVw2L9EYC9o+PASADd5VRjaSbua5bWQyceavQG5uc7ozE9p7CbeED+aF7RBTEKR51aRPiKQvY8burDKroA1/XfKbFZ4UdNag8XnwritSjO5lyl3Z1cFTlWDXynr089EueSZCzrPJzOishdomJfa9XdynWKKShRNz8R/LEJZ0ro5rsvYK6hHA31269R858tGmjQQUu8gUZeL+U60RtAi7LB/MeKuD5osfyL4BOifRUE5zuqHV5wPryf+mlEGWKuRfOrHU8mtcX3P5ZZTlP4Xx/mER+0uRsqbn5bKebpm3/VXNtTvKd8n/5Px/wSdZeRLui9ZfAARR2EBARIzyh2k+sIj0CK4LiY5NEiJIb3AJZ0ViAJXziaCeRZXEPXz58efR3Hc7BbDt3CAj3XQg+D9dkteFWmtapZ8w7oaPDeN/kq6UE02BMfTExL6W2Lhp2vj8PcoZVPKO7nKS9aD6vSi5cZfY6PveQYne41stFMrTHbCsAftDq548B0gHyGZXU11quDg9k6VPp0XkJlDx1FvB/gy9CPMoImiEofYETGKlVz1YyK1KYiel3ldZNaCen8jj3bkLZCjGRp19vhL68hAnQmWxCUoZpdeaygKD0lB8jRvTcm+DU2M9p2LwEmXgjqrS+7psHyrq6hInyT2HHicV1YmPI46+YBBffwgQ==
  template:
    metadata:
      name: minio-bearer-token
      namespace: victoriametrics
    type: Opaque
