---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgCWnw9wp5s3Dsoh7fAhultCA2/cb4mnSUdG9hkiFn+MyzqsPZYcGSZHNgVoSBMigJuQ7r1ucVMUknWejcMFcjeJ5lDgxdK9LBjTtHdcj1nkqmywFB3BlSSzYsTjOk6MiHAOq/5h1JZhQkz096tiYvuM64EJdp3y4N1REQGkG/CC+3Nf9EVN+t5Mvg7sL0u7AR7nBpdc+tvOGG50lxqXr2DukmPd3kcEhxeGYXqgzxqNaUhA3dtSDVhRaWUrfOc8LgY9Ti13bHI7r4b4s24uHN4TdE4cIYudmr0JF+LB8JoVepw1geHM9hhmkcc4mOoJIWY+lBfbRa939pJ2QWjhxebgKVIWJcC5NQLaJQqRiPlMAAbrQ8LWon/o6SMz0BUdiR9uVnyU7kAV6ktoW9S2NcSAijkqJuRuTAUvxpBxoRq0urXDJmLJzXRBbVhB6EihX2yF5i3F4V6CKGe0ecoa543ETXsLFqaGfty8Sdf0gUwEjH4sFFoqD+u31xFc9jdBXRGSiwKJ1lnr+OrXkaC2xbpzEPvHIComaaycFZDwZHSqFYSnKmP+9H1/Lo7+N+ufUyDR0dlNh/dGsR83o2UMgPlAHnFjdp6u/nG6DuxSICrMsDsoNer7YzSbFJtdlATdnULawfWM1rqSCzO4H7zRYM5XA95x96EU7sFXZzG6BS3y5ShVRh/PS38m+tEB3A4IGxgkFOWzciJMMnXqLO5yOgDfanPtgqAa3e9ikT4MwgGE6ZI0j0Sibfoj8pitoSQ6ixDi9yOeQp4Yqt0EVcsUxpUU
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
