apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgB3n16pGfhTEam5iQsGcnqmqCWmtroaLNosaJiB7V32BVUqhYrGkXw9rvvF+Pjra0OOLA/Eveh9UqD06iHAiZRn8XsvQW3o4r+UjQHz/+UEArcv99oAJjETUOSwL5a5QxltLsVd3MoLYmQg4YunnLwAfX/BnWL86vKAhe/mB4bJKpU/G4PBUpTVS9H0jvhhcBOg2gGJGfLvuAfW9yx9yNOhHYhoqJHHCrzmik5A8lQWOuhHb7W+Kc/3xGBq861OwnSJsNU3obuYFNmtCaJNzZjZq1t/QUfcayq9MWqb1t4k6sBz4E/CXQJ2fJUS3MvmehnqJk6IEmlxc7rEiGwoPAZD1K3Oj7TpybKi7UbxUPG+xq+c/oYQ14deWRWMpPUPTHlxpZKthrV+UyxybK+oFqnV/EmpeiwtBlE6XTNj1LEbHAETxQYYumFexK6nTl22p2Ws64FvktHChjCE6I1anx9VmvQQfBGzxa8lKw8w/aV1nCy3UQQ/NixRn1KSq+W5ZoJr4Boh19HHgOMnS1ZohvQwGv5K+2yqbehYruUyDW4nhoBQTkG0S6lCBeEGTPNTdGrAWD4ybG/ubSePkSvmLD5XOkewYy5N3onaEFrfqF+ockbdCT98ahK/EOI/d9Mi/Eo7I9AH24XkCdYNL1/qtbHYUrYrNCeVXnSlYcc+eWTXzJIz2EKSJSjnsvk6BHyvQzu7qnRISHjD5LtPIk8f8JDsoOvtuDh1jlRQ0Sb8V5pelZihVBrSSRc5C/z0ZW6rlt4=
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
