---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgDfOCjikPKExedBwIGQouecUGfMvIvbgmVIw/K80smQr1wuYonviJy1BlmFTjh/FVZTwrPqhBKTV2GvjFYrZGISCZuXvuQkd3d/EGrjowLKIWUVbWBZ8h7y9YKcfNej6jTEiBoW5HbOPtp9uSnss2K3SUyX2cM9VkaaK4gAUZ/Q/IslBodDHW4u6vp0SUrzvp1G/iOH90oTJr6T0RvtMmlsBP+gQQe5ShBlorbZBPpspUbmoC7KKvFqbkR86/EUPMr4xANYIGcweMtwVbAEGMPKjd/whH4g4yK6D8Uhyf/Fn2dcj1mhllfzDW+8TxZXpojtJB7NODWaLi8gVkzcKBDDkvyKeWC9BgAduxNBeEb4BpsnvQOeEzgWXAYJYWDYpaSwU3hEJzfQSK2E7y3DmVuySyok6fi0hajPZffJGCzkF3CrGFlZYeNN6nzP8aVfLkZrUKKkaE2QWp+3R0Ze2/ZUMD/yXVrVb1s00lg5Z5gJmOF7wvk7r4xN+jKS3UVIUcUPOEQhXnLnFTW9sdMHJgxEu54XqLSwsV6kNkC3pYFPGxWt0mZZNN7JHRVVFGM3Cf8aj2ZXnG12GfQXtu0sb4uMvW2tQMhOWmfyQaY3f/nBAK7wa5/gnMKmcPYeYHx9RdI7iism27e37qjMB+PMRHWhZIfsI22bjT67uZMveSJy6nsO53sFH9pGHa9CDUuBTXcqsxjPSYjoxNLYnRZFuD6iOYEY/cjOBfhpJ0YshOWafeEbS2rfc63zwQS9Jemmp0IAvdZLbge6bdmLGswWyo8DWpU=
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
