---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgCZorErqLvNSL9UZerMxqmaBkCe5GJ0Rd5Z1LWknlJJurYQtVcQ8uYoDAfp8Ji8QtXLr3Q70p3c8MBNCSLb/k2/YolzZsS6cJUslRbyel7ItNW70Nvb6BrRlOLHCYjgu4GH0mTY+0BcAeIsikDLgkm+Ycd2ePPtCtibiZduGhqaXSqEJXIReZTy0+GdiA4/jhXer0075CiYG35miAJ/KLRVt9t2N+mIz8wQA0/levSrphV65ZCPrz54jexbZBFrcN82hdiPOYUFItRInI7M2ilEupCTBAK4Z6qG7NDIwbwyuSBUPeWKifa/dz1I/Z/GCuk64aOqFnMG8hf0W7ws/J65M4lIm5GfIgd3mzWsbSxbkeG6C9H7VUBOvHaNLG+NJ9K7ZeUXE8hphlwMNQRb5z3nmkyRVLVLkwqwgFG4BoxcxvpzuZgd8R5Nr4A5GMeIigdFszGmCYN8aJrASTSYbJ6DKvQoaL0NcOo2A3Z+518DskzfnYdXZF3mapPYFAhwed+wfQr+1u70Pipr7TDH3vASKePQOB5iVYdhfzfkV3J56o26qs04wV7VcewWL+vhGPhRSQs2p/9EyGFvZ3OXFAT0aByC+jniTE4/VvYeEMH145jpHuVY90nxKTObrJreGqmmmRedtNn432bHzmFlHPkITZp0vuC4URlLl0Yj7KnY10UUab8Nvn1yj4K4GwrZgXNY0bZLAKmCuyQ3G4aRILeH0pNDfNmfR+CDzgQEPISmSbcuP7vxnQKBXIPitMVpPbvpVgmt7qnovVULSFQGQkVByDNBeCGPMW2nrtzkncB59YSi7sXrmnPVn1x/4brihlSLoZIlDGvfHNNeiLD9isEmnGdsS+DwSu0yeACBlKWxwA==
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
