---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgAqC3q4ZBBaYD9g7DH5XUCXVMFq70+iN4ZYNBNXJLTXqvOLUrmwVRoYh9bHg4rmTrxQGKo7Ghg/aKjm3MC4XqladkS9BEQScwv1TDpTEn4U0tQAM+MSL9wF9gXSxsdJPtf9Ux5lJAlw7zsOM2IKCPxQtwxNu46gFKQN5kF4djSOua7Kh6EqGjzJZfGckkBtIWrBjTBb0iPw9/joAhm10eLHLUx5Vt7mswgTDZuK7aEMm4kIB543KNK6wHKQ1tPsDXPd6aYxlOI0eXIIYaQiEnbwgSfBJCLMRBl1/8pAgQq0mZyW0n6QODWybgj+j81W1wNtLu/MuLVvR8QX1WMggqmYdIu6hIpa9ZlBYRY7rMnqV8YP6fkyskg3QxsEvCUpWZPpxK4+Wl/mYNLAxL30NpvtOdPE+tEV8xzIZe5vIjRc4EhSTHWb+8Y5TvI7YwDIVVRdqkF8jsoaJQyelBM5Rm2tI7B6+Py1JmjLJbGUxUMH4H8BjL7eaoWmF64cObsZflI0j4+CwPGfB5gehnv3XBozZFU6ZiiuEgYs269PolhJ1AwHyl1YmFZ5pCKd8Oi91oVNX69CMq50TNbWeJuDeApgyAruwTdZebYvu1pZn/Ic8ypMHseHhEd58cccjbSHcqeNkzSx/M2TyjvfAtHEHs4EBh27JzzvXc2DzmQbiGLpi30GS3egeV686nbUo73EE4eDO21AIF7jxYUxbRILQrgkYjx3sAFOXd64ubuEYw39Lkor0vro/pWKM1p4wWFYKCnShQSBAFrdQqSauyvOvylHhpn8HOnSBiQCnkbVeT69XIZ5QbT1QpBx
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
