---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgBe83yMSssHNn7Z+arlMM9UKCP9z3RVYBZzo4VN+b0Gvp+w8D/vMOFZDzyznXcdfuQAMOZSaWpTHbQoJaHGb3FK+zYxX2C7DcahMYB1iS1ssmT52QC2y7Cu7KaTy+ZmBEeTlXErILzI1ldM6zHsS0DVJ5YGtOcktwFVhyeMGQGZWPWGakTBf/YDcACLMhnaMWljJDUXC9Jh3mBTfH36p5Sg1hBD1x7Se2jLdVvGNgBLDhc+YujAKhYJRSBxbuYGhHPyEjDOCZlE1DCZvgqx+twkw7ICC+AQaDMSxs/Yt2b53UYE1nRK6ZoBAxJclTGKOwNv0fPkcBj2GKQ+9Nr/d2Ng1YZmmRGDmSMzL8spxIAL1qrUZZoJ4Smow1zwQAPM9Hy3BUS3CdF673A84XtyT57P0A3j3q8V6aRQYn73iFXzikIaf1lwo1a3+Q7N6zzBc/J+PQThGDMLrtx85PAA8k0Hz1Ow0iZePT5/52VK5/WY64DC8ZmLlqDwTdbtntzunKH4P4ViypTsf1vQYQAltvgPceNdcmVps9c507VrB5dXdNoaCt7iP25LEog/dpQxIFnB3MCdxpoLkuYejQ3DkEQkhAM7wGv5X4ltr2UECfMxkn8IERA8aCHf9C3fY3En1hlwFtzo4EKHvNPasfhoeFdyXA5pCcoDQP6NDS2s1OX6oOA56uPGY4ysStODFAjmMTxAR0jWSkB2GaWYDsW6qLgdcnxYanrVeOOAhVfNRmFpnu9laNrqI5l6kl/QnzmxZSbX5vRDtGF6OZ9wFmzXsRvs
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
