---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgDM6T0JR1car9ZxcWmUS8/LDdWH+8Hg5JF9WlXwbb9DjpWx15vXqopBgde2WZkus5fXxU72EL2n850gkcze8a7vHdEP5uRcJSv54jpkM5IEewmThEHPhJIxVf0vIqaLHsuWp9G1a9kpJ7ADmOcPt9BBFO7cpogQoZn1HcfEPgho+mWLgzTohCjYEBEwCQeb0pc5qZRg8j6lzZEZ0xzx2xuJFD7M65SvzdJut41CzalVCQxP/iP0mAh3cCsOFZsIWxi3xlZoXnm6hvOzAAWYd3IKXjCnFinAIfx4eG+WEFlU9+54P/kH3sj7UkuwYFykKBTdlFcm+vvMXugkq5ZwPeVu1QURBOJdE3Yd7MfOTscWTQlg7gSy72wz0KXFU02A/fzWd5bTTyJfKGY5Nzx3Fmj9yh7n4tYEv41OCOxlPxsU3kP5+yYl8YnTFjIDVYsaTrxneaEna8diUKKFvb9RelQIeN49LtbqShOptAxPKE5Z2ApGJNbwnCf7383OuXtVAWfwBKcWd0+ReVZTZGyyjN1PBZy/CoQM/tJ9ZwyaW5LTRUf1Y6DRQ/ACN38OUGiUVa5sRBd3T0QorTNrTkyZdZYSwxGtuCK8lJN6XnyKG2Rd1CPtBE+8G7My/ClOmbHmf5VAXQNUYm8MM0YNwlUmsTIXDo8FpcmLKG+eM9/MmS5JjeAR0Aj2+iuIm69lN7D2YWUq7x+pZgW1gWHBIb+firkaFRRAsMgpUCFamVnAwFMTLHNU173/tyCpaDWouA==
  template:
    metadata:
      name: db-encryption
      namespace: homarr
    type: Opaque
