apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: minio
  name: minio
addressType: IPv4
endpoints:
  - addresses:
    - {{ .Values.endpoint.minio.ip }}
ports:
  - name: http
    port: 9000
    protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: minio-console
  name: minio-console
addressType: IPv4
endpoints:
  - addresses:
    - {{ .Values.endpoint.minioConsole.ip }}
ports:
  - name: http
    port: 9001
    protocol: TCP
