apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fritzbox-cloudflare-dyndns-chart
spec:
  hostnames:
    - {{ .Values.httproute.hostnames0 }}
  parentRefs:
    - name: shared-gateway
      namespace: kube-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fritzbox-cloudflare-dyndns-chart-http
          port: 8080
