apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github - argocd-apps:
            - abbr: GH
              href: https://github.com/steled/argocd-apps/issues/127
        - Github - homelab:
            - abbr: GH
              href: https://github.com/steled/homelab/issues/59
        - Github - homelab-terraform:
            - abbr: GH
              href: https://github.com/steled/homelab-terraform/issues/173
        - Github - terraformmodules:
            - abbr: GH
              href: https://github.com/steled/terraformmodules/issues/65
  services.yaml: |
    - Internal Services:
        - Alertmanager:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prometheus.svg
            href: http://alert.{{ .Values.domain }}/
            description: prometheus alertmanager
        - Argo CD:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/argo-cd.svg
            href: https://gitops.{{ .Values.domain }}/
            description: argocd gitops
        - Grafana:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/grafana.svg
            href: http://monitoring.{{ .Values.domain }}/
            description: grafana dashboards
        - Longhorn:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/rancher-longhorn.svg
            href: https://volume.{{ .Values.domain }}/
            description: longhorn ui
        - Minio:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/minio.svg
            href: https://console.s3.{{ .Values.domain }}/
            description: minio s3 console

    # - My Second Group:
    #     - My Second Service:
    #         href: http://localhost/
    #         description: Homepage is the best

    # - My Third Group:
    #     - My Third Service:
    #         href: http://localhost/
    #         description: Homepage is ðŸ˜Ž
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
